version: '3.3'

services:
  postgres:
    image: postgres:alpine
    container_name: heimdall_db
    hostname: heimdall_db
    environment:
      POSTGRES_USER: heimdall
      POSTGRES_PASSWORD: heimdall
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  webserver:
    build: ./web
    container_name: heimdall_web
    hostname: heimdall_web
    env_file: .env
    volumes:
      - ./web/src:/home/www
    depends_on:
      - postgres
    ports:
      - 80:80
