version: '3.3'

services:
  postgres:
    image: postgres:alpine
    container_name: heimdall_db
    hostname: heimdall_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: heimdall
      POSTGRES_PASSWORD: heimdall
    ports:
      - 5432:5432

  webserver:
    build: ./web
    container_name: heimdall_web
    hostname: heimdall_web
    depends_on:
      - postgres
    ports:
      - 80:80
    environment:
      APP_ENV: prod
      SERVER_NAME: heimdall.watch
